version: "3.3"
   
services:
  mysql:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/db:/var/lib/mysql
    container_name: db

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_PASSWORD=password
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL_HOST=db
      - KC_DB_URL_PORT=3306
      - KC_DB_USERNAME=keycloak
    ports:
      - 8080:8080
    depends_on:
      - mysql

    
